Repository Project-MONAI/monai-deploy-messaging, pull requests merged in 2022-04, with the labels that each got.

#1 Messaging API with RabbitMQ support
  .editorconfig
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/pull_request_template.md
  .github/workflows/ci.yml
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  GitReleaseManager.yaml
  GitVersion.yml
  NuGetDefense.json
  codecov.yml
  global.json
  nuget.config
  src/.sonarlint/Monai.Deploy.Messaging.slconfig
  src/.sonarlint/project-monai_monai-deploy-messaging/CSharp/SonarLint.xml
  src/.sonarlint/project-monai_monai-deploy-messagingcsharp.ruleset
  src/AssemblyInfo.cs
  src/Messaging/API/IMessageBrokerPublisherService.cs
  src/Messaging/API/IMessageBrokerSubscriberService.cs
  src/Messaging/AssemblyInfo.cs
  src/Messaging/Common/BlockStorageInfo.cs
  src/Messaging/Common/Log.cs
  src/Messaging/Common/MessageReceivedEventArgs.cs
  src/Messaging/Configuration/ConfigurationException.cs
  src/Messaging/Configuration/ConfigurationKeys.cs
  src/Messaging/Configuration/MessageBrokerServiceConfiguration.cs
  src/Messaging/Messages/ExportCompleteMessage.cs
  src/Messaging/Messages/ExportRequestMessage.cs
  src/Messaging/Messages/JsonMessage.cs
  src/Messaging/Messages/Message.cs
  src/Messaging/Messages/MessageBase.cs
  src/Messaging/Messages/WorkflowRequestMessage.cs
  src/Messaging/Monai.Deploy.Messaging.csproj
  src/Messaging/RabbitMq/RabbitMqMessagePublisherService.cs
  src/Messaging/RabbitMq/RabbitMqMessageSubscriberService.cs
  src/Messaging/Test/DummyTest.cs
  src/Messaging/Test/Monai.Deploy.Messaging.Test.csproj
  src/Monai.Deploy.Messaging.sln
  src/coverlet.runsettings
Labels: enhancement

#2 Target .NET Standard 2.1
  CONTRIBUTING.md
  README.md
  src/Messaging/Messages/ExportRequestMessage.cs
  src/Messaging/Messages/JsonMessage.cs
  src/Messaging/Messages/Message.cs
  src/Messaging/Messages/MessageBase.cs
  src/Messaging/Monai.Deploy.Messaging.csproj
Labels: enhancement

#4 [Breaking] Unit tests for RabbitMQ plugin
  .github/pull_request_template.md
  src/Messaging/AssemblyInfo.cs
  src/Messaging/InternalVisible.cs
  src/Messaging/Monai.Deploy.Messaging.csproj
  src/Messaging/RabbitMq/IServiceCollectionExtension.cs
  src/Messaging/RabbitMq/RabbitMqConnectionFactory.cs
  src/Messaging/RabbitMq/RabbitMqMessagePublisherService.cs
  src/Messaging/RabbitMq/RabbitMqMessageSubscriberService.cs
  src/Messaging/Test/DummyTest.cs
  src/Messaging/Test/ExportCompleteMessageTest.cs
  src/Messaging/Test/JsonMessageTest.cs
  src/Messaging/Test/Monai.Deploy.Messaging.Test.csproj
  src/Messaging/Test/RabbitMq/RabbitMqMessagePublisherServiceTest.cs
  src/Messaging/Test/RabbitMq/RabbitMqMessageSubscriberServiceTest.cs
  src/Messaging/Test/WorkflowRequestMessageTest.cs
Labels: breaking

#3 Update README.md
  .github/workflows/ci.yml
  README.md
Labels: minor

#9 Add subscription no requeue reject
  src/Messaging/API/IMessageBrokerSubscriberService.cs
  src/Messaging/RabbitMq/RabbitMqMessageSubscriberService.cs
Labels: enhancement

#11 Additional FailureReasons
  src/Messaging/Events/FailureReason.cs
Labels: enhancement

#13 Ability to convert Message to JsonMessage<T>
  src/Messaging/API/IMessageBrokerPublisherService.cs
  src/Messaging/API/IMessageBrokerSubscriberService.cs
  src/Messaging/Common/Log.cs
  src/Messaging/Messages/Message.cs
  src/Messaging/RabbitMq/RabbitMqConnectionFactory.cs
  src/Messaging/RabbitMq/RabbitMqMessagePublisherService.cs
  src/Messaging/RabbitMq/RabbitMqMessageSubscriberService.cs
  src/Messaging/Test/JsonMessageTest.cs
  src/Messaging/Test/RabbitMq/RabbitMqMessagePublisherServiceTest.cs
  src/Messaging/Test/RabbitMq/RabbitMqMessageSubscriberServiceTest.cs
Labels: enhancement
