Repository Project-MONAI/monai-deploy-messaging, pull requests merged in 2022-11, with the labels that each got.

#95 Update licenses
  .github/workflows/ci.yml
  doc/dependency_decisions.yml
  third-party-licenses.md
Labels: build

#96 Release/0.1.9
  .github/workflows/ci.yml
  .github/workflows/package-cleanup.yml
  doc/dependency_decisions.yml
  src/Messaging/Monai.Deploy.Messaging.csproj
  src/Messaging/Tests/Monai.Deploy.Messaging.Tests.csproj
  src/Plugins/RabbitMQ/Tests/Monai.Deploy.Messaging.RabbitMQ.Tests.csproj
  third-party-licenses.md
Labels: build

#97 adding message timings
  src/Plugins/RabbitMQ/Logger.cs
  src/Plugins/RabbitMQ/Monai.Deploy.Messaging.RabbitMQ.csproj
  src/Plugins/RabbitMQ/RabbitMqMessageSubscriberService.cs
Labels: enhancement

#98 AC-824 task manager rabbit connection resiliency issues
  src/Plugins/RabbitMQ/Factory/CreateChannelArguments.cs
  src/Plugins/RabbitMQ/Factory/IRabbitMQConnectionFactory.cs
  src/Plugins/RabbitMQ/Factory/RabbitMqConnectionFactory.cs
  src/Plugins/RabbitMQ/Logger.cs
  src/Plugins/RabbitMQ/Publisher/PublisherServicHealthCheckBuilder.cs
  src/Plugins/RabbitMQ/Publisher/PublisherServiceRegistration.cs
  src/Plugins/RabbitMQ/Publisher/RabbitMqMessagePublisherService.cs
  src/Plugins/RabbitMQ/Subscriber/RabbitMqMessageSubscriberService.cs
  src/Plugins/RabbitMQ/Subscriber/SubscriberServicHealthCheckBuilder.cs
  src/Plugins/RabbitMQ/Subscriber/SubscriberServiceRegistration.cs
Labels: bug

#104 Expose event delegate for clients to handle connection issues
  doc/dependency_decisions.yml
  src/Messaging/API/ConnectionErrorArgs.cs
  src/Messaging/API/IMessageBrokerSubscriberService.cs
  src/Messaging/Tests/IServiceCollectionExtensionsTests.cs
  src/Messaging/Tests/Monai.Deploy.Messaging.Tests.csproj
  src/Plugins/RabbitMQ/Factory/CreateChannelArguments.cs
  src/Plugins/RabbitMQ/Factory/IRabbitMQConnectionFactory.cs
  src/Plugins/RabbitMQ/Factory/RabbitMqConnectionFactory.cs
  src/Plugins/RabbitMQ/Logger.cs
  src/Plugins/RabbitMQ/Monai.Deploy.Messaging.RabbitMQ.csproj
  src/Plugins/RabbitMQ/Subscriber/RabbitMqMessageSubscriberService.cs
  src/Plugins/RabbitMQ/Tests/Monai.Deploy.Messaging.RabbitMQ.Tests.csproj
  third-party-licenses.md
Labels: bug

#105 release/0.1.11
  doc/dependency_decisions.yml
  src/Messaging/API/ConnectionErrorArgs.cs
  src/Messaging/API/IMessageBrokerSubscriberService.cs
  src/Messaging/Tests/IServiceCollectionExtensionsTests.cs
  src/Messaging/Tests/Monai.Deploy.Messaging.Tests.csproj
  src/Plugins/RabbitMQ/Factory/CreateChannelArguments.cs
  src/Plugins/RabbitMQ/Factory/IRabbitMQConnectionFactory.cs
  src/Plugins/RabbitMQ/Factory/RabbitMqConnectionFactory.cs
  src/Plugins/RabbitMQ/Logger.cs
  src/Plugins/RabbitMQ/Monai.Deploy.Messaging.RabbitMQ.csproj
  src/Plugins/RabbitMQ/Subscriber/RabbitMqMessageSubscriberService.cs
  src/Plugins/RabbitMQ/Tests/Monai.Deploy.Messaging.RabbitMQ.Tests.csproj
  third-party-licenses.md
Labels: build

#108 Adding fixed up test
  src/Plugins/RabbitMQ/Tests/RabbitMQHealthCheckTest.cs
Labels: enhancement

#106 Remove RMQ dependency from the base API library
  src/Messaging/API/ConnectionErrorArgs.cs
  src/Messaging/Events/ExportCompleteEvent.cs
  src/Messaging/Monai.Deploy.Messaging.csproj
  src/Plugins/RabbitMQ/Monai.Deploy.Messaging.RabbitMQ.csproj
  src/Plugins/RabbitMQ/Publisher/RabbitMqMessagePublisherService.cs
  src/Plugins/RabbitMQ/Subscriber/RabbitMqMessageSubscriberService.cs
Labels: bug

#111 Release/0.1.12
  src/Messaging/API/ConnectionErrorArgs.cs
  src/Messaging/Events/ExportCompleteEvent.cs
  src/Messaging/Monai.Deploy.Messaging.csproj
  src/Plugins/RabbitMQ/Factory/RabbitMqConnectionFactory.cs
  src/Plugins/RabbitMQ/Monai.Deploy.Messaging.RabbitMQ.csproj
  src/Plugins/RabbitMQ/Publisher/RabbitMqMessagePublisherService.cs
  src/Plugins/RabbitMQ/RabbitMQHealthCheck.cs
  src/Plugins/RabbitMQ/Subscriber/RabbitMqMessageSubscriberService.cs
  src/Plugins/RabbitMQ/Tests/RabbitMQHealthCheckTest.cs
Labels: build

#113 Release/0.1.13
  .github/workflows/ci.yml
  GitVersion.yml
  src/Messaging/API/ConnectionErrorArgs.cs
Labels: build

#125 Release/0.1.16
  src/Messaging/Common/LoggingDataDictionary.cs
  src/Plugins/RabbitMQ/Factory/IRabbitMQConnectionFactory.cs
  src/Plugins/RabbitMQ/Factory/RabbitMqConnectionFactory.cs
  src/Plugins/RabbitMQ/Publisher/RabbitMqMessagePublisherService.cs
  src/Plugins/RabbitMQ/Subscriber/RabbitMqMessageSubscriberService.cs
  src/Plugins/RabbitMQ/Tests/RabbitMqMessagePublisherServiceTest.cs
Labels: build

#129 Release/0.1.16
  src/Plugins/RabbitMQ/ChannelType.cs
  src/Plugins/RabbitMQ/Factory/IRabbitMQConnectionFactory.cs
  src/Plugins/RabbitMQ/Factory/RabbitMqConnectionFactory.cs
  src/Plugins/RabbitMQ/Publisher/RabbitMqMessagePublisherService.cs
  src/Plugins/RabbitMQ/RabbitMQHealthCheck.cs
  src/Plugins/RabbitMQ/Subscriber/RabbitMqMessageSubscriberService.cs
  src/Plugins/RabbitMQ/Tests/RabbitMQHealthCheckTest.cs
  src/Plugins/RabbitMQ/Tests/RabbitMqMessagePublisherServiceTest.cs
  src/Plugins/RabbitMQ/Tests/RabbitMqMessageSubscriberServiceTest.cs
Labels: build

#134 Update packages
  doc/dependency_decisions.yml
  src/Messaging/Monai.Deploy.Messaging.csproj
  src/Messaging/Tests/Monai.Deploy.Messaging.Tests.csproj
  src/Plugins/RabbitMQ/Tests/Monai.Deploy.Messaging.RabbitMQ.Tests.csproj
  third-party-licenses.md
Labels: dependencies

#136 Update GitVersion.yml
  GitVersion.yml
Labels: build
