Repository Project-MONAI/monai-deploy-messaging, pull requests merged in 2023-08, with the labels that each got.

#209 Release/0.1.24
  doc/dependency_decisions.yml
  src/Messaging/API/IMessageBrokerSubscriberService.cs
  src/Messaging/Common/ServiceException.cs
  src/Messaging/Events/ExportCompleteEvent.cs
  src/Messaging/Events/ExportRequestEvent.cs
  src/Messaging/Events/WorkflowRequestEvent.cs
  src/Messaging/Monai.Deploy.Messaging.csproj
  src/Messaging/Tests/IServiceCollectionExtensionsTests.cs
  src/Messaging/Tests/Monai.Deploy.Messaging.Tests.csproj
  src/Messaging/Tests/WorkflowRequestMessageTest.cs
  src/Plugins/RabbitMQ/Factory/RabbitMqConnectionFactory.cs
  src/Plugins/RabbitMQ/Monai.Deploy.Messaging.RabbitMQ.csproj
  src/Plugins/RabbitMQ/Publisher/RabbitMqMessagePublisherService.cs
  src/Plugins/RabbitMQ/Subscriber/RabbitMqMessageSubscriberService.cs
  src/Plugins/RabbitMQ/Tests/Monai.Deploy.Messaging.RabbitMQ.Tests.csproj
  src/Plugins/RabbitMQ/Tests/Unit/RabbitMqMessageSubscriberServiceTest.cs
  third-party-licenses.md
Labels: enhancement

#211 Remove unused references and clean up licenses
  doc/dependency_decisions.yml
  src/Messaging/Events/ExportCompleteEvent.cs
  src/Messaging/Monai.Deploy.Messaging.csproj
  src/Messaging/Tests/Monai.Deploy.Messaging.Tests.csproj
  src/Plugins/RabbitMQ/Factory/RabbitMqConnectionFactory.cs
  src/Plugins/RabbitMQ/Monai.Deploy.Messaging.RabbitMQ.csproj
  src/Plugins/RabbitMQ/Publisher/RabbitMqMessagePublisherService.cs
  src/Plugins/RabbitMQ/Subscriber/RabbitMqMessageSubscriberService.cs
  src/Plugins/RabbitMQ/Tests/Monai.Deploy.Messaging.RabbitMQ.Tests.csproj
  third-party-licenses.md
Labels: dependencies, .NET, security

#213 Main
  doc/dependency_decisions.yml
  src/Messaging/API/IMessageBrokerSubscriberService.cs
  src/Messaging/Common/ServiceException.cs
  src/Messaging/Events/ExportRequestEvent.cs
  src/Messaging/Events/WorkflowRequestEvent.cs
  src/Messaging/Tests/IServiceCollectionExtensionsTests.cs
  src/Messaging/Tests/WorkflowRequestMessageTest.cs
  src/Plugins/RabbitMQ/Subscriber/RabbitMqMessageSubscriberService.cs
  src/Plugins/RabbitMQ/Tests/Unit/RabbitMqMessageSubscriberServiceTest.cs
  third-party-licenses.md
Labels: build

#215 Workflow Request Event to support multiple sources/modalities
  src/Messaging/Events/WorkflowRequestEvent.cs
  src/Messaging/Tests/WorkflowRequestMessageTest.cs
Labels: breaking

#217 Add ACR enum in DataService
  src/Messaging/Common/BlockStorageInfo.cs
  src/Messaging/Common/Credentials.cs
  src/Messaging/Common/Storage.cs
  src/Messaging/Events/EmailRequestEvent.cs
  src/Messaging/Events/ExportCompleteEvent.cs
  src/Messaging/Events/ExportRequestEvent.cs
  src/Messaging/Events/TaskCallbackEvent.cs
  src/Messaging/Events/TaskCancellationEvent.cs
  src/Messaging/Events/TaskDispatchEvent.cs
  src/Messaging/Events/TaskUpdateEvent.cs
  src/Messaging/Events/WorkflowRequestEvent.cs
  src/Messaging/Monai.Deploy.Messaging.csproj
  src/Messaging/Tests/WorkflowRequestMessageTest.cs
  src/Plugins/RabbitMQ/Monai.Deploy.Messaging.RabbitMQ.csproj
Labels: enhancement

#218 Release/0.2.1
  src/Messaging/Common/BlockStorageInfo.cs
  src/Messaging/Common/Credentials.cs
  src/Messaging/Common/Storage.cs
  src/Messaging/Events/EmailRequestEvent.cs
  src/Messaging/Events/ExportCompleteEvent.cs
  src/Messaging/Events/ExportRequestEvent.cs
  src/Messaging/Events/TaskCallbackEvent.cs
  src/Messaging/Events/TaskCancellationEvent.cs
  src/Messaging/Events/TaskDispatchEvent.cs
  src/Messaging/Events/TaskUpdateEvent.cs
  src/Messaging/Events/WorkflowRequestEvent.cs
  src/Messaging/Monai.Deploy.Messaging.csproj
  src/Messaging/Tests/WorkflowRequestMessageTest.cs
  src/Plugins/RabbitMQ/Monai.Deploy.Messaging.RabbitMQ.csproj
Labels: build

#222 Release/1.0.0
  src/Messaging/Events/ExportCompleteEvent.cs
Labels: build
