Repository Project-MONAI/monai-deploy-messaging, pull requests merged in 2024-01, with the labels that each got.

#270 Update project to .NET 8
  .github/workflows/ci.yml
  doc/dependency_decisions.yml
  global.json
  src/Messaging/Common/LoggingDataDictionary.cs
  src/Messaging/Common/MessageConversionException.cs
  src/Messaging/Common/MessageValidationException.cs
  src/Messaging/Common/ServiceException.cs
  src/Messaging/Configuration/ConfigurationException.cs
  src/Messaging/Monai.Deploy.Messaging.csproj
  src/Messaging/Tests/Common/ArtifactTypesTests.cs
  src/Messaging/Tests/Monai.Deploy.Messaging.Tests.csproj
  src/Plugins/RabbitMQ/Monai.Deploy.Messaging.RabbitMQ.csproj
  src/Plugins/RabbitMQ/Tests/Integration/HealthCheckTest.cs
  src/Plugins/RabbitMQ/Tests/Monai.Deploy.Messaging.RabbitMQ.Tests.csproj
  src/Plugins/RabbitMQ/Tests/Unit/RabbitMQHealthCheckTest.cs
  src/Plugins/RabbitMQ/Tests/Unit/RabbitMqMessagePublisherServiceTest.cs
  src/Plugins/RabbitMQ/Tests/Unit/RabbitMqMessageSubscriberServiceTest.cs
  third-party-licenses.md
Labels: dependencies, .NET

#273 Release 2.0.0
  .github/workflows/ci.yml
  doc/dependency_decisions.yml
  global.json
  src/Messaging/API/IMessageBrokerSubscriberService.cs
  src/Messaging/Common/LoggingDataDictionary.cs
  src/Messaging/Common/MessageConversionException.cs
  src/Messaging/Common/MessageValidationException.cs
  src/Messaging/Common/ServiceException.cs
  src/Messaging/Configuration/ConfigurationException.cs
  src/Messaging/Monai.Deploy.Messaging.csproj
  src/Messaging/Tests/Common/ArtifactTypesTests.cs
  src/Messaging/Tests/Monai.Deploy.Messaging.Tests.csproj
  src/Plugins/RabbitMQ/Monai.Deploy.Messaging.RabbitMQ.csproj
  src/Plugins/RabbitMQ/Tests/Integration/HealthCheckTest.cs
  src/Plugins/RabbitMQ/Tests/Monai.Deploy.Messaging.RabbitMQ.Tests.csproj
  src/Plugins/RabbitMQ/Tests/Unit/RabbitMQHealthCheckTest.cs
  src/Plugins/RabbitMQ/Tests/Unit/RabbitMqMessagePublisherServiceTest.cs
  src/Plugins/RabbitMQ/Tests/Unit/RabbitMqMessageSubscriberServiceTest.cs
  third-party-licenses.md
Labels: build

#290 allowing prefectCount to be configurable
  .github/workflows/ci.yml
  doc/dependency_decisions.yml
  src/Plugins/RabbitMQ/ConfigurationKeys.cs
  src/Plugins/RabbitMQ/Subscriber/RabbitMqMessageSubscriberService.cs
  src/Plugins/RabbitMQ/Tests/Integration/ReliabilityTest.cs
Labels: enhancement

#291 Release/2.0.1
  .github/workflows/ci.yml
  doc/dependency_decisions.yml
  src/Plugins/RabbitMQ/ConfigurationKeys.cs
  src/Plugins/RabbitMQ/Monai.Deploy.Messaging.RabbitMQ.csproj
  src/Plugins/RabbitMQ/Subscriber/RabbitMqMessageSubscriberService.cs
  src/Plugins/RabbitMQ/Tests/Integration/ReliabilityTest.cs
  third-party-licenses.md
Labels: enhancement
